### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Any comments or changes needed?  I think this should be ready to merge and get a long prefix build out on the `conda-forge` channel.

**Comment by jakirkham** [comment]
Sorry @jjhelmus I've been down with a cold for most of the week.

Also I saw some comment somewhere (can't find it ATM) about uploads not working with `conda-build` version 2. Perhaps related to this ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/39 ). Is this true? Do you know anything about it?

**Comment by jjhelmus** [comment]
conda/conda-build#950 seems to have revered to a single argument version of `bldpkg_path` and so uploading now works with the current version of `conda-build`, 2.0.12.

**Comment by jakirkham** [comment]
You know more than I at this point. Let's merge and see.

**Comment by jakirkham** [comment]
Seems to be working so far. Going to assume it is a non-issue.

**Comment by jakirkham** [comment]
This is completed.

**Pull request merged**
