### PR TITLE
make sure to use the correct shared lib on win

### PR DESCRIPTION
**Pull request by k-dominik**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

this PR makes sure that one windows the correct version of lemon is included. The first working build will be `*_10` once https://github.com/conda-forge/lemon-feedstock/pull/18 is merged!

Not sure about the syntax here, btw, is `lemon 1.3.1>=*_10  # [win]` correct to include only builds 10 and up on windows?

alternatively, one could of course delete all lemon windows packages up to now (they should not be functioning properly anyway).

### CODE REVIEW

**Comment by k-dominik** [comment]
@conda-forge-admin please re-render.

**Comment by k-dominik** [comment]
hi @conda-forge/vigra I'm pretty sure I didn't get the pinning syntax right, but last time I checked, there weren't many docs on that:

got the following build error:

```pytb
conda.exceptions.ResolvePackageNotFound: 
  - lemon[version='1.3.1>=*_3']
```

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
It seems to have picked up the new build:
```
    lemon:           1.3.1-h7f30438_3           conda-forge
```

honestly, for build numbers, you can assume that it will take the largest one unless something else is off with the pinnings.

**Comment by k-dominik** [comment]
> It seems to have picked up the new build:
> 
> ```
>     lemon:           1.3.1-h7f30438_3           conda-forge
> ```
> 
> honestly, for build numbers, you can assume that it will take the largest one unless something else is off with the pinnings.

I mean cool that it works, in a sense, but for us it is vital that we can access the functionality in vigra that relies on lemon. But I can also implement a pin on our side I guess.

**Comment by hmaarrfk** [comment]
I see. You want to pin the run time dependency. Not too sure how

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Pull request merged**
