### PR TITLE
Use new NumPy pinnings

### PR DESCRIPTION
**Pull request by jakirkham**
Update this feedstock to use the [new style of NumPy pinnings in conda-forge]( https://conda-forge.org/docs/meta.html#building-against-numpy ). This should cutdown on the CI resources this feedstock uses and allow the deployed packages to be used with older versions of NumPy if needed. Also re-render to take advantage of the new CircleCI matrix and eliminate the NumPy CI matrices (as they are unneeded with the new NumPy pinnings).

### CODE REVIEW

**Comment by jakirkham** [comment]
Not sure if these older versions of NumPy are still supported/would work with VIGRA. Would be good if someone could inform me either way. If not, we can certainly bump these as needed.

cc @ukoethe

**Comment by jakirkham** [comment]
Well it seems to pass in any event. So maybe this is ok.

**Comment by jakirkham** [comment]
Going ahead with this since it passes the tests and their hasn't been any indication from others that it won't work. If it turns out to be a problem, happy to revert and pull packages as needed.

**Comment by ukoethe** [comment]
Thanks for taking care of this!

**Pull request merged**
