### PR TITLE
Use conda-forge-pinning 2018.07.19

### LINKED ISSUE #41: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #41.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #41

### CODE REVIEW

**Comment by jakirkham** [comment]
Looks like the library for Boost.Python renamed itself again. 😒

**Comment by isuruf** [comment]
How about adding a symlink?

**Comment by jakirkham** [comment]
Yeah, I have a commit like that locally, which I was going to push. Was waiting to see how AppVeyor responded.

What would you recommend we do for Windows?

**Comment by jakirkham** [comment]
@conda-forge-admin, please lint.

**Comment by jakirkham** [comment]
@isuruf, do you have any advice for Windows here? Seem to have gotten everything else except Windows to work.

**Comment by jakirkham** [comment]
Hmm...looks like this may be a Boost.Python bug after all. If so, the Boost 1.68.0 version fixes this. Will test it in the compiler rebuild PR ( https://github.com/conda-forge/vigra-feedstock/pull/43 ). If that works, will merge that and close this.

xref: https://github.com/boostorg/python/issues/193

**Comment by jakirkham** [comment]
The newer version of Boost fixes the Windows build issue. So closing in favor of PR ( https://github.com/conda-forge/vigra-feedstock/pull/43 ).

**Pull request closed without merging**
