### PR TITLE
Add patch for cpp17 support

### PR DESCRIPTION
**Pull request by constantinpape**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This patch applies https://github.com/ukoethe/vigra/pull/500, which replaces the deprecated bind1st and bind2nd with bind.
This should enable building vigra with c++17 on macOs.

### CODE REVIEW

**Comment by constantinpape** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Thank you for this. im curious why we need this.

Chances are, your patch will be accepted upstream by the time conda-forge moves to cpp17

**Comment by hmaarrfk** [comment]
FWIW, the patch looks pretty good. i just want to make sure I understand.

**Comment by hmaarrfk** [comment]
i think our build.sh sets the cpp standard. we should remove it with this. Thanks!

**Comment by hmaarrfk** [comment]
One last question, given that this is a compile change, how does this affect your workflow? Aren't you downloading the packages from conda-forge using conda?

How does compiling with C++17 change downstream compatibility for your application?

**Comment by constantinpape** [comment]
> One last question, given that this is a compile change, how does this affect your workflow? Aren't you downloading the packages from conda-forge using conda?
> 
> How does compiling with C++17 change downstream compatibility for your application?

Like I said, I am only using vigra as a header only dependency downstream, so changing the compilation flags here does not change anything for me; but I need the patches applied in order to build with c++17 myself.

I guess that if there are any downstream dependencies that are linking to the vigra libraries they would need to change to build with c++17 now. (Which I think is fair, given that this is the default on conda-forge now).

**Pull request merged**
