### PR TITLE
Arch migrator: try cross compiling

### PR DESCRIPTION
**Pull request by k-dominik**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by k-dominik** [comment]
@conda-forge-admin, please rerender

**Comment by k-dominik** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Do we still want the dual HDF5 builds.

**Comment by k-dominik** [comment]
There are quite a few pipelines running here :D - how about we do them now once also for the new archs to allow for more flexibility there, and then drop `1.12.2`?

**Comment by k-dominik** [comment]
Also, how is your experience with `test: native_and_emulated` - Are there emulators on the build machines for arch64?

**Comment by hmaarrfk** [comment]
Ok on HDF5. 

Emulation is done through qemu which is installed on the docker images.

**Comment by stuarteberg** [comment]
@k-dominik would you like to add yourself to the maintainers list?

**Comment by jakirkham** [comment]
Looks like some conflicts crept in here

Do we want to merge this?

**Comment by hmaarrfk** [comment]
yes.

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
