### PR TITLE
fix non-tuple indexing inside vigra

### PR DESCRIPTION
**Pull request by k-dominik**
make sure to index via tuples. numpy will error out since 1.23

https://github.com/ukoethe/vigra/pull/475

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by k-dominik** [comment]
@conda-forge-admin, please rerender

**Comment by k-dominik** [comment]
I'm currently reproducing the windows build... Let's see. Don't have access to a non-mtl Mac today.

**Comment by hmaarrfk** [comment]
what is `mtl`? I've added a few more patches in attempts to solve this problem, but the cause seems to be elsewhere. https://github.com/conda-forge/vigra-feedstock/pull/97

**Comment by k-dominik** [comment]
> what is `mtl`? I've added a few more patches in attempts to solve this problem, but the cause seems to be elsewhere. #97

heya, sorry I'm such a lazy typer. Since I'm still jumping between architectures I often give the silicon stuff a `-mtl` postfix...

**Comment by hmaarrfk** [comment]
why was this closed?

**Pull request closed without merging**
