### PR TITLE
Rebuild python310 + patches

### PR DESCRIPTION
**Pull request by k-dominik**
trying to see if ci would pass...

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/vigra-feedstock/pull/83

### CODE REVIEW

**Comment by k-dominik** [comment]
any idea about fixing the win-py310-npy1.21 build? @hmaarrfk (tagging you because you seem pretty active in here)

**Comment by k-dominik** [comment]
ah yeah, I'll get a fresh windows build machine ready today and look into it some more

**Comment by jakirkham** [comment]
Was about to say it does appear to build `vigranumpytest.cp310-win_amd64.pyd`. Almost wonder if something isn't getting copied over correctly (like a `CMakeLists.txt` bug)?

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
what about trying this patch:
https://github.com/ukoethe/vigra/pull/485

**Comment by k-dominik** [comment]
weird, in the last iteration (before rerender) the python 3.9/numpy119 build worked...

**Comment by hmaarrfk** [comment]
I think i found the issue. See patch in: https://github.com/conda-forge/vigra-feedstock/pull/85

**Comment by k-dominik** [comment]
closing in favor of #85

**Pull request closed without merging**
